version: "3.8"
services:
  db:
    container_name: "next-db-dev"
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=next-db-dev
    ports:
      - "5433:5432"
    volumes:
      - next-db:/var/lib/postgresql/data

volumes:
  next-db:
    name: next-db
    driver: local